# build-bossdata.ps1
#  Wraps authored bossdata.json into bossdata.js — a global the static site loads offline
#  (file:// can't fetch JSON). Boss combat data (damage dealt + weaknesses) is AUTHORED, not
#  datamined: edit bossdata.json, then run this. Never hand-edit bossdata.js.
$ErrorActionPreference = "Stop"
$src = Join-Path $PSScriptRoot "bossdata.json"
$out = Join-Path $PSScriptRoot "bossdata.js"

$json = Get-Content $src -Raw -Encoding UTF8 | ConvertFrom-Json

# Re-emit sorted by boss name so the generated diff is stable. Coerce list fields to
# arrays explicitly — PS 5.1 ConvertTo-Json would otherwise unwrap a 1-element list to a
# scalar, which breaks `.map()` in the browser.
$ordered = [ordered]@{}
foreach ($k in ($json.PSObject.Properties.Name | Sort-Object)) {
  $v = $json.$k
  $clean = [ordered]@{ deals = @($v.deals); weak = @($v.weak) }
  if ($v.PSObject.Properties['resist'] -and @($v.resist).Count -gt 0) { $clean.resist = @($v.resist) }
  if ($v.PSObject.Properties['note'] -and $v.note) { $clean.note = [string]$v.note }
  $ordered[$k] = $clean
}

$body = $ordered | ConvertTo-Json -Depth 8 -Compress
$header = "/* AUTO-GENERATED by build-bossdata.ps1 from bossdata.json. Do not hand-edit. */`r`n"
Set-Content -Path $out -Value ($header + "window.BOSS_INFO = " + $body + ";`r`n") -Encoding UTF8
Write-Host "bossdata.js written: $($ordered.Count) bosses"
